server:
  port: 20000
spring:
  application:
    name: coupon-template-serv
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/coupon
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: coupon
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行，破坏生产数据
      ddl-auto: none
    # 在日志中打印经过格式化的SQL语句
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false